//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AGRITEDPXEntities : DbContext
    {
        public AGRITEDPXEntities()
            : base("name=AGRITEDPXEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CROP> CROP { get; set; }
        public virtual DbSet<EQUIPMENT> EQUIPMENT { get; set; }
        public virtual DbSet<FARMER> FARMER { get; set; }
        public virtual DbSet<FERTILIZER> FERTILIZER { get; set; }
        public virtual DbSet<FIELD> FIELD { get; set; }
        public virtual DbSet<QUALITY> QUALITY { get; set; }
        public virtual DbSet<RESERVATION> RESERVATION { get; set; }
        public virtual DbSet<SUPPLIER> SUPPLIER { get; set; }
    }
}
