//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class RESERVATION
    {
        
        public int ReservationId { get; set; }
        public Nullable<int> FieldId { get; set; }
        public Nullable<int> FarmerId { get; set; }
        public Nullable<int> CropId { get; set; }
        public Nullable<int> EquipmentId { get; set; }
        public Nullable<int> FertilizerId { get; set; }
        public decimal TotalPrice { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public string Status { get; set; } = "pending";
    
        public virtual CROP CROP { get; set; }
        public virtual EQUIPMENT EQUIPMENT { get; set; }
        public virtual FARMER FARMER { get; set; }
        public virtual FERTILIZER FERTILIZER { get; set; }
        public virtual FIELD FIELD { get; set; }
    }
}
